### ISSUE TITLE
E22 commands difference

### ISSUE THREAD

**Issue by aleksander1084** [KrisKasprzak/EBYTE#20]
Hi!
I have a question, have you been testing your library with E22 modules?
I think there might be an issue because they have different command formats and responds.
As well as for E22 programming mode is different, for E32 (M0 M1) was (1 1), for E22 it's (0 1).

Sorry that I can't test it myself since since my modules are still being shipped what takes years this days.

Thanks in advance for any help,
Aleksander

**Comment by KrisKasprzak** [comment]
Aleksander,
According to the EBYTE datasheets, both modules are (0,0) for transmit mode, and (1,1) for program mode. WOR and config mode are different--this seems very odd. I suspect it's a typo on the EBYTE side but I have just send a question to the EBYTE manufacturer to clarify the discrepancy. 


Thanks,
Kris Kasprzakkris.kasprzak@yahoo.com
 

    On Wednesday, June 10, 2020, 06:25:26 AM CDT, Aleksander Felisiak <notifications@github.com> wrote:  
 
 


Hi!
I have a question, have you been testing your library with E22 modules?
I think there might be an issue because they have different command formats and responds.
As well as for E22 programming mode is different, for E32 (M0 M1) was (1 1), for E22 it's (0 1).

Sorry that I can't test it myself since since my modules are still being shipped what takes years this days.

Thanks in advance for any help,
Aleksander

**Comment by aleksander1084** [comment]
I just today received my modules after 8 weeks of shipping.
I tried to connect it via USB to the hex serial monitor. Sending message in deep sleep mode is not causing any respond.
In E22 documentation on the top of page 17 is a note to use Mode 2 (CONFIG mode to access registers), and as well command format is different than for E32.
To read a whole configuration in E32 command was: 0xC1 0xC1 0xC1 
for E22 it would be 0xC1 0x00 0x04, and only this new command gives responds and only in mode2 (CONFIG).

I found another interesting thing that suggest that EByte makes documentation based on COPY/PASTE. 
Based on chapter 7.3 (page21) of documentation default parameters are: C0 00 00 62 00 00,
and I was confused when I get: 00 00 00 62 00 17 03, so I converted binary from registers definitions into hex ant looks like they made a mistake on default parameters.

Thanks,
Aleksander

**Comment by Ashraff93** [comment]
Any solution when using E22 instead of E32 since i have same problem about this?

**Comment by aleksander1084** [comment]
Based on Krise's library I had build my own dedicated for E22, there is several differences between E22 and E32 + there is several mistakes in a Datasheet that I have reported to E-byte but haven't seen them fixed.

**Comment by Dukat-Gul** [comment]
> Based on Krise's library I had build my own dedicated for E22, there is several differences between E22 and E32 + there is several mistakes in a Datasheet that I have reported to E-byte but haven't seen them fixed.

Just bumping this to see if @aleksander1084 has had any responses back from e-byte? And/or are you willing to share (please) the work you have done to make your dedicated E22 build? I am keen to give it a try on my E22s. Cheers

**Comment by Raniita** [comment]
> Based on Krise's library I had build my own dedicated for E22, there is several differences between E22 and E32 + there is several mistakes in a Datasheet that I have reported to E-byte but haven't seen them fixed.

I add to @Dukat-Gul comment as to whether it would be possible for you (@aleksander1084 ) to share with us the modifications you have made to make the E22 work. I am currently designing a project, with e32, but im looking at modules with RSSI feature (e22 or e220). It would be very interesting to see how you have implemented it. 

Thank you all!! :D
