### ISSUE TITLE
Ebyte library conflict with Adafruit_BME280_Library

### ISSUE THREAD

**Issue by eriktheV-king** [KrisKasprzak/EBYTE#44]
Hello Kris
Whereas the library is working fine with E30 and E32 modules, as soon as the Adafruit_BME280_Library is used, multiple compile errors appear in relation to MODE_NORMAL
I found out that both libraries are using a parameter MODE_NORMAL.
I try to rename all MODE_NORMAL in your Ebyte library EBYTE.h and EBYTE.cpp to MODE_NORMAAL and now everything works neatly together with the Adafruit library.
Good luck and thanks for this nice piece of work!

**Comment by KrisKasprzak** [comment]
Good tip. I'm afraid if I change the library, implementations will break--people using SetMode in their programs. 
I can add a note to the read me.

Thanks,
Kris ***@***.***
 

    On Thursday, October 14, 2021, 02:10:32 PM CDT, eriktheV-king ***@***.***> wrote:  
 
 


Hello Kris
Whereas the library is working fine with E30 and E32 modules, as soon as the Adafruit_BME280_Library is used, multiple compile errors appear in relation to MODE_NORMAL
I found out that both libraries are using a parameter MODE_NORMAL.
I try to rename all MODE_NORMAL in your Ebyte library EBYTE.h and EBYTE.cpp to MODE_NORMAAL and now everything works neatly together with the Adafruit library.
Good luck and thanks for this nice piece of work!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
