### ISSUE TITLE
E220-400T22S Transmitter and Receiver Questions. Need Assistance Please.

### ISSUE THREAD

**Issue by krishank652** [KrisKasprzak/EBYTE#76]
Greetings,

Currently, I'm engaged with the LoRa E220-400T22S device, aiming to transmit signals from the transmitter unit and receive them via the receiver unit.

I have several inquiries and would be grateful for your assistance:

1. Is it necessary to utilize a TTL UART Device for configuring key parameters in the module? If so, is this device compatible: [TTL UART MODULE](https://robu.in/product/cp-2102-6-pin/)?
2. Is it feasible to configure this LoRa module with Arduino? If yes, could you provide guidance on the process?
3. Does the provided library support this LoRa E220-400T22S module?
4. Given that I'm utilizing an 8KB microcontroller, the size of the library appears to be too large. How can I optimize the program's code? Are there any non-essential segments within the library that can be excluded while using it?

Thank you for your assistance.

**Comment by KrisKasprzak** [comment]
1. EBYTE has special hardware programming modules, see https://www.cdebyte.com/product_serch/E15-USB/1/ The company also has software for programming the module
2. Yes, I do it all the time, see the examples
3. No it does not, 
4. what are you trying to do? Do you want a library to a) program the module once, b) change settings at runtime, or c) send/receive data? if (a) try the programmer I listed above if (b) since you have only 8K MCU, you will probably need to write your own programming code, if (c) you don't need a library, creating a struct and using Serial.send(....) and Serial.readBytes(...) is all you need.
